# Generated by Django 5.2.7 on 2025-11-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Код товара (SKU)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Продано'),
        ),
        migrations.AlterField(
            model_name='productkey',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен (не продан)'),
        ),
        migrations.AlterField(
            model_name='productkey',
            name='key_value',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ключ / данные аккаунта'),
        ),
    ]
